version: "3.7"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    container_name: web-app123
    volumes:
      - app-data:/app

volumes:
  app-data: